# Discovering Reddit communities
02807 Computational Tools for Data Science, Group 31

## 1. Data

In [ ]:
# Import necessary libraries
import pandas as pd
from pathlib import Path

In [ ]:
# Paths to the files saved by data_fetch.ipynb
data_folder = Path("data")

posts_path = data_folder / "datascience_posts_2026-09.csv"
comments_path = data_folder / "datascience_comments_2026-09.csv"

# Load the datasets
posts = pd.read_csv(posts_path, parse_dates=["created_at"])
comments = pd.read_csv(comments_path, parse_dates=["created_at"])

# Check the results
print(f"Posts: {len(posts)}")
print(f"Comments: {len(comments)}")

display(posts.head())
display(comments.head())

Posts: 71
Comments: 946

,id,subreddit,author,created_utc,title,selftext,score,num_comments,url,created_at
0,1w484pi,datascience,bobbe_,1788258953,Pulling data from access orchestrate to build ...,[removed],1,1,https://www.reddit.com/r/datascience/comments/...,2026-09-01 10:35:53+00:00
1,1w4c38i,datascience,DataScienceGuy_,1788269475,"At senior levels, where do you draw the line b...",I’ve been in data science/analytics for about ...,22,29,https://www.reddit.com/r/datascience/comments/...,2026-09-01 13:31:15+00:00
2,1w67e3p,datascience,Trick-Interaction396,1788442016,How are LLMs used in predictive modeling and a...,I am DS with 20 YOE but I've been managing lat...,54,37,https://www.reddit.com/r/datascience/comments/...,2026-09-03 13:26:56+00:00
3,1w6qtza,datascience,informatica6,1788486439,"How do you guys ""show your work""",I use a google sheet to list my major projects...,12,14,https://www.reddit.com/r/datascience/comments/...,2026-09-04 01:47:19+00:00
4,1w70acq,datascience,Repulsive-Look-9787,1788516835,Is sql important for a data analyst internship,[removed],1,1,https://www.reddit.com/r/datascience/comments/...,2026-09-04 10:13:55+00:00

,id,subreddit,author,created_utc,body,score,link_id,parent_id,created_at
0,p732qz6,datascience,[deleted],1788221176,[removed],1,t3_1w3klb5,t3_1w3klb5,2026-09-01 00:06:16+00:00
1,p732zzz,datascience,aaronswar43,1788221258,Had an offer from Amazon and I decided to decl...,1,t3_1w3klb5,t3_1w3klb5,2026-09-01 00:07:38+00:00
2,p734a57,datascience,Dependent-Aide-388,1788221677,I have worked at multiple FAANGs and I do regr...,1,t3_1w3klb5,t3_1w3klb5,2026-09-01 00:14:37+00:00
3,p734irn,datascience,ExecutiveFingerblast,1788221756,There's an old Eddie izzard bit about jfk in G...,2,t3_1w3n6p7,t1_p72u2fd,2026-09-01 00:15:56+00:00
4,p7370l7,datascience,CJDrew,1788222591,It varies but probably 40-50. Plus on call wee...,11,t3_1w3klb5,t1_p730wy3,2026-09-01 00:29:51+00:00